"DbUser" = "psqladmin"
"DbPassword" = "H@Sh1CoR3!ABC"
"DbName" = "app"
"DbPort" = "5432"
"DbHost" = "postgresql-server-kg.postgres.database.azure.com"
"DbHostName" = "postgresql-server-kg"
"ListenHost" = "0.0.0.0"
"ListenPort" = "3000"